Fix sonic-vpp build issue in master (#1731)
why
compilation of sonic-vpp failed with below error.

In file included from vpp/SwitchVpp.h:8,
from VirtualSwitchSaiInterface.cpp:19:
vpp/TunnelManager.h:104:32: error: field 'm_router_mac' has incomplete type 'std::array<unsigned char, 6>'
104 | std::array<uint8_t, 6> m_router_mac;

what this PR does
Add missing include.

how it is verified
sonic-vpp build is successful with the fix.

Signed-off-by: Yue Gao <yuega2@cisco.com>